version: '2'
services:

  datomic:
    image: datomic
    ports:
      - 4334:4334
      - 4335:4335
      - 4336:4336
    volumes:
      - datomic:/opt/datomic-pro-0.9.5561/data

  ventas:
    image: ventas
    ports:
        - ${LOCAL_PORT}:${SERVER__PORT}
    depends_on:
      - datomic
    env_file:
        - .env
    volumes:
        - ./storage:/storage

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  chrome:
    image: robcherry/docker-chromedriver:latest
    ports:
      - 4444:4444
    environment:
      - "CHROMEDRIVER_WHITELISTED_IPS=''"
    privileged: true

volumes:
  elasticsearch:
    driver: local
  datomic:
    driver: local