version: '2'
services:

  datomic:
    image: datomic
    ports:
      - 4334:4334
      - 4335:4335
      - 4336:4336
    volumes:
      - datomic:/opt/datomic-pro-0.9.5561/data
    environment:
      - XMX=-Xmx512M
      - XMS=-Xms512M

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.watermark.high=0.95
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  elasticsearch:
    driver: local
  datomic:
    driver: local
