apiVersion: v1
kind: Service
metadata:
  name: ventas
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "4001"
    port: 4001
    targetPort: 4001
  selector:
    app: ventas
    tier: backend
status:
  loadBalancer: {}
